### ISSUE TITLE
transmit rate is very slow

### ISSUE THREAD

**Issue by qiangao97** [nexmonster/nexmon_csi_bin#3]
I installed in Pi 4 with nexmon_csi_bin, but when I start collect csi, there shows that only several packets are received per seconds. Can you give me some advice?

**Comment by qiangao97** [comment]
In the 'Free you CSI' paper, 1 Tx 1 Rx situation can receive thousands of packets per second

**Comment by qiangao97** [comment]
[@zeroby0](https://github.com/zeroby0)

**Comment by zeroby0** [comment]
Heyo!

The 'Free your CSI' paper isn't mine :) It's by Jakob Link: https://github.com/seemoo-lab/nexmon_csi . I'm just a user trying to make it easier to access CSI.

- https://github.com/seemoo-lab/nexmon_csi/discussions or
- https://github.com/nexmonster/nexmon_csi/discussions

are better places to ask this question, because this repository is only for storing the compiled binaries and scripts to install them. The actual code, and more importantly, the people who can answer your questions, are on those repositories.

I describe my method of generating wireless traffic so CSI can be collected here: https://github.com/seemoo-lab/nexmon_csi/issues/280#issuecomment-1309794681 and here: https://github.com/seemoo-lab/nexmon_csi/issues/280#issuecomment-1315110188

Please post your next questions there, there's a lot more people who can help you there :)
